//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class login {
    
    /// <summary>
    /// TextBox1 control for username.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox TextBox1;
    
    /// <summary>
    /// RequiredFieldValidator1 control.
    /// </summary>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    /// <summary>
    /// TextBox2 control for password.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox TextBox2;
    
    /// <summary>
    /// RequiredFieldValidator2 control.
    /// </summary>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
    
    /// <summary>
    /// Button1 control for login.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button Button1;
    
    /// <summary>
    /// Label1 control for error messages.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label Label1;
}